"""add onboarding fields and placement tests

Revision ID: f845f9c2346c
Revises: 725415bf12a7
Create Date: 2026-06-27 01:11:45.542810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f845f9c2346c'
down_revision: Union[str, Sequence[str], None] = '725415bf12a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('result_level', sa.Enum('beginner', 'intermediate', 'advanced', name='placementlevel'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('onboarded', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('experienced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experienced')
    op.drop_column('users', 'onboarded')
    op.drop_table('placement_tests')
    # ### end Alembic commands ###
